version: '2'
services:

  ### Mysql container
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bingo
      MYSQL_DATABASE:hyperledger
      MYSQL_USER: vagrant
      MYSQL_PASSWORD:bingo
      MYSQL_ROOT_HOST:192.168.33.10
